services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pousadinha_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN:-MTMzOTIwNDEwNzM5ODkzODYyNA.G_zg28.5IC_q7NnPVC4Zdg3xGgvdbiJHXn4xWw34He81I}
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-pousadinha}?sslmode=disable
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-pousadinha}
      - DB_SSLMODE=disable
      - API_PORT=:8080
      - GACHA_ENABLED=true
      - GACHA_PUBLIC_URL=https://gachatest.pousada.space
      - GACHA_MEDIA_DIR=/app/data/gacha
      - CATALOG_ADMIN_PASSWORD=${CATALOG_ADMIN_PASSWORD:-RCpfWGsExAlP-xPLmvhV--S1113mvIlO}
    volumes:
      - ./data/gacha:/app/data/gacha
      - ./config.json:/app/config.json
    ports:
      - "${HOST_API_PORT:-8085}:8080"
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    networks:
      - pousadinha_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: pousadinha_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN:-eyJhIjoiMDhkZDg4YTEyOGVkYjMyN2Q3YWIwOGU2OTdjNWFhYWMiLCJ0IjoiZmFjMjdjMGMtYmUyZC00YzBkLWJkMjQtYWFhOTJlNTA5MTNmIiwicyI6Ik1qVmxaV1ppTjJRdE5ERTFaUzAwTTJFM0xUZzNPV0l0TUdReFl6ZzBNamxqTlRoaCJ9}
    networks:
      - pousadinha_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - bot

  postgres:
    image: postgres:16-alpine
    container_name: pousadinha_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-pousadinha}
    ports:
      - "${HOST_DB_PORT:-5435}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-pousadinha}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - pousadinha_network

volumes:
  postgres_data:
    name: pousadinha_postgres_data

networks:
  pousadinha_network:
    name: pousadinha_network
    driver: bridge
